#!/usr/bin/env python3
"""Build immutable VP-G07 public-perturbation evidence artifacts.

This is a post-freeze evidence transcription step.  It does not query or
replace the sealed NCBI snapshot, and refuses to overwrite any expected G07
artifact.  The evidence values below were independently read from the public
records named in ``source_evidence.tsv`` on 2026-09-09.
"""

from __future__ import annotations

import csv
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


VP = Path(__file__).resolve().parents[1]
OUT = VP / "08_external_reference"
FREEZE = VP / "01_protocol" / "VP_G07_external_scope_rule_freeze_v1.json"
G06 = VP / "validation" / "VP_G06_enrichment_COMPLETE.json"
SNAPSHOT = OUT / "ncbi_search_results.json"

EXPECTED_HASHES = {
    G06: "67740aa1ab08bbd067ca9c85aead06cbbccce84db2e3e0c3308f16e6dfe2a75e",
    FREEZE: "8ff4fa705eeab9262ddbe28e3b78e8b4907812c4515b2a8dca62bf5aa70a4d2c",
    SNAPSHOT: "4a6bf603a0255983ebe623d84ccd076478884df3fd298c356f76b9482a2fe100",
}

OUTPUTS = [
    OUT / "public_perturbation_target_coverage.tsv",
    OUT / "search_log.tsv",
    OUT / "source_evidence.tsv",
    OUT / "gears_applicability.tsv",
    OUT / "unipert_g2cp_applicability.json",
    OUT / "VP_G07_external_scope_report.md",
    OUT / "artifact_manifest.sha256.tsv",
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_tsv(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, delimiter="\t", extrasaction="raise")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    for path, expected in EXPECTED_HASHES.items():
        if not path.is_file() or sha256(path) != expected:
            raise SystemExit(f"HOLD_INPUT_DRIFT: {path}")
    if json.loads(G06.read_text(encoding="utf-8")).get("status") != "PASS":
        raise SystemExit("HOLD_INPUT_DRIFT: VP-G06 is not PASS")
    if any(path.exists() for path in OUTPUTS):
        existing = [str(path) for path in OUTPUTS if path.exists()]
        raise SystemExit("Refusing to overwrite VP-G07 artifact(s): " + "; ".join(existing))

    accessed = datetime.now(timezone.utc).isoformat()
    snapshot = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    genes = {"EFNB2": "1948", "LRRC17": "10234", "TYMS": "7298"}

    coverage_fields = [
        "target_gene", "canonical_symbol_verified", "perturbation_type", "single_or_combination",
        "cell_line_or_type", "cell_context_tier", "species", "time", "dose_or_intensity",
        "dataset", "accession", "has_controls", "downloadable", "download_url",
        "matches_corpus_cavernosum_fibroblast", "evidence_status", "source_url",
        "primary_citation", "notes", "evidence_ids",
    ]
    coverage = [
        {"target_gene":"EFNB2", "canonical_symbol_verified":"YES_NCBI_Gene_1948", "perturbation_type":"adenoviral overexpression", "single_or_combination":"single", "cell_line_or_type":"cultured lymphatic endothelial cells (LECs)", "cell_context_tier":"T2_RELATED_HUMAN", "species":"Homo sapiens", "time":"NOT_REPORTED", "dose_or_intensity":"NOT_REPORTED", "dataset":"Effect of EphrinB2 on gene expression in cultured LECs under hypoxia", "accession":"GSE279328", "has_controls":"YES_Ad-NC_3_vs_Ad-EFNB2_4", "downloadable":"YES_PUBLIC_GEO_SUPPLEMENTARY_ENDPOINT", "download_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE279nnn/GSE279328/", "matches_corpus_cavernosum_fibroblast":"NO", "evidence_status":"VERIFIED_DATASET_MEMBER", "source_url":"https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE279328", "primary_citation":"NOT_REPORTED", "notes":"Bulk RNA-seq; all samples were hypoxia-treated. GEO SOFT states Ad-NC or Ad-Efnb2 and warns that raw files were lost; public supplementary endpoint remains reachable, but raw-read availability is not claimed.", "evidence_ids":"E04;E05"},
        {"target_gene":"EFNB2", "canonical_symbol_verified":"YES_NCBI_Gene_1948", "perturbation_type":"CRISPRa (dCas9-VPR activation)", "single_or_combination":"single", "cell_line_or_type":"U266 plasma-cell multiple-myeloma line", "cell_context_tier":"T4_HUMAN_CELL_LINE", "species":"Homo sapiens", "time":"NOT_REPORTED", "dose_or_intensity":"dCas9-VPR plus EFNB2 gRNA2; selection-agent dose is not perturbation dose", "dataset":"Bulk RNA-seq after Overexpression of EFNB2 in U266 Multiple Myeloma Cells", "accession":"GSE256290", "has_controls":"YES_non-targeting_scrambled_cgRNA_5_vs_EFNB2_gRNA2_5", "downloadable":"YES_PUBLIC_GEO_SUPPLEMENTARY_ENDPOINT", "download_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE256nnn/GSE256290/", "matches_corpus_cavernosum_fibroblast":"NO", "evidence_status":"VERIFIED_DATASET_MEMBER", "source_url":"https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE256290", "primary_citation":"NOT_REPORTED", "notes":"Bulk RNA-seq. SOFT overall design explicitly identifies dCas9-VPR and EFNB2 promoter-targeting gRNA2; it reports 80-100-fold RNA increase by qPCR.", "evidence_ids":"E06;E07"},
        {"target_gene":"EFNB2", "canonical_symbol_verified":"YES_NCBI_Gene_1948", "perturbation_type":"CRISPRi knockdown", "single_or_combination":"single", "cell_line_or_type":"KOLF2.1J human induced pluripotent stem cells", "cell_context_tier":"T3_OTHER_PRIMARY_HUMAN", "species":"Homo sapiens", "time":"144H", "dose_or_intensity":"NOT_REPORTED", "dataset":"CM4AI perturbation cell atlas", "accession":"PRJNA1173491", "has_controls":"YES_NTC_DOCUMENTED_IN_PRIMARY_RECORD", "downloadable":"YES_PUBLIC_RAW_SRA;PROCESSED_FIGSHARE_OBJECT_PRIVATE", "download_url":"https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1173491", "matches_corpus_cavernosum_fibroblast":"NO", "evidence_status":"VERIFIED_DATASET_MEMBER", "source_url":"https://s3.perturbseqr.maayanlab.cloud/data/cm4ai.gmt.gz", "primary_citation":"Nourreddine et al., Nature Biotechnology (2026), doi:10.1038/s41587-026-03199-w", "notes":"Target membership is machine-readable in the public PerturbSeqr CM4AI GMT as EFNB2::KOLF2.1J::hiPSCs::144H::::KD::CRISPRi. Raw read project is public; do not equate this with access to the private processed object.", "evidence_ids":"E08;E09;E10"},
        {"target_gene":"LRRC17", "canonical_symbol_verified":"YES_NCBI_Gene_10234", "perturbation_type":"NOT_VERIFIED", "single_or_combination":"NOT_VERIFIED", "cell_line_or_type":"NOT_VERIFIED", "cell_context_tier":"TX_UNKNOWN", "species":"NOT_VERIFIED", "time":"NOT_REPORTED", "dose_or_intensity":"NOT_REPORTED", "dataset":"NO_VERIFIED_HIT_IN_FROZEN_TARGETED_SOURCES", "accession":"NOT_APPLICABLE", "has_controls":"NOT_VERIFIED", "downloadable":"NOT_VERIFIED", "download_url":"NOT_APPLICABLE", "matches_corpus_cavernosum_fibroblast":"NO_VERIFIED_T1_HIT", "evidence_status":"NO_VERIFIED_HIT", "source_url":"ncbi_search_results.json", "primary_citation":"NOT_APPLICABLE", "notes":"Within the sealed 18-query NCBI snapshot and the exact-target checks of publicly reachable CM4AI and Replogle-derived catalog records, no qualifying direct LRRC17 transcriptomic genetic-perturbation record was verified. This is a bounded audit result, not a claim of global absence.", "evidence_ids":"E02;E03;E11;E12"},
        {"target_gene":"TYMS", "canonical_symbol_verified":"YES_NCBI_Gene_7298", "perturbation_type":"shRNA knockdown", "single_or_combination":"single", "cell_line_or_type":"A549 lung adenocarcinoma line", "cell_context_tier":"T4_HUMAN_CELL_LINE", "species":"Homo sapiens", "time":"NOT_REPORTED", "dose_or_intensity":"NOT_REPORTED (selection agents reported separately in SOFT)", "dataset":"Thymidylate synthase drives the phenotypes of epithelial-to-mesenchymal transition in non-small cell lung cancer", "accession":"GSE148589", "has_controls":"YES_scrambled_pLKO_2_vs_shTS_2_in_A549", "downloadable":"YES_PUBLIC_GEO_SUPPLEMENTARY_ENDPOINT", "download_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE148nnn/GSE148589/", "matches_corpus_cavernosum_fibroblast":"NO", "evidence_status":"VERIFIED_DATASET_MEMBER", "source_url":"https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE148589", "primary_citation":"doi:10.1038/s41598-020-74525-3; PMID:33024270", "notes":"Bulk RNA-seq. Only the A549 shTS versus pLKO comparison is direct TYMS perturbation; Calu-1 TS-high/low reporter-sorted samples are retained in source evidence as non-coverage for this target record unit.", "evidence_ids":"E13;E14"},
        {"target_gene":"TYMS", "canonical_symbol_verified":"YES_NCBI_Gene_7298", "perturbation_type":"CRISPRi knockdown", "single_or_combination":"single", "cell_line_or_type":"K562 chronic myelogenous leukemia line", "cell_context_tier":"T4_HUMAN_CELL_LINE", "species":"Homo sapiens", "time":"day8", "dose_or_intensity":"P1P2 guide pair", "dataset":"Replogle et al. 2022 K562 genome-wide Perturb-seq", "accession":"Figshare article 20029387; K562_gwps", "has_controls":"NOT_VERIFIED_IN_TARGET_RECORD", "downloadable":"YES_PUBLIC_FIGSHARE_PROCESSED_H5AD_ENDPOINT", "download_url":"https://ndownloader.figshare.com/files/35774443", "matches_corpus_cavernosum_fibroblast":"NO", "evidence_status":"VERIFIED_DATASET_MEMBER", "source_url":"https://maayanlab.cloud/Harmonizome/gene_set/9464_TYMS_P1P2/Replogle%2Bet%2Bal.%2C%2BCell%2C%2B2022%2BK562%2BGenome-wide%2BPerturb-seq%2BGene%2BPerturbation%2BSignatures", "primary_citation":"Replogle et al., Cell (2022), doi:10.1016/j.cell.2022.05.013", "notes":"Exact target record is the public 9464_TYMS_P1P2 CRISPRi signature. The GEARS distributed K562-essential subset is a different filtered subset and must not be used to negate membership in full K562_gwps.", "evidence_ids":"E15;E16"},
        {"target_gene":"TYMS", "canonical_symbol_verified":"YES_NCBI_Gene_7298", "perturbation_type":"CRISPRi knockdown", "single_or_combination":"single", "cell_line_or_type":"KOLF2.1J human induced pluripotent stem cells", "cell_context_tier":"T3_OTHER_PRIMARY_HUMAN", "species":"Homo sapiens", "time":"144H", "dose_or_intensity":"NOT_REPORTED", "dataset":"CM4AI perturbation cell atlas", "accession":"PRJNA1173491", "has_controls":"YES_NTC_DOCUMENTED_IN_PRIMARY_RECORD", "downloadable":"YES_PUBLIC_RAW_SRA;PROCESSED_FIGSHARE_OBJECT_PRIVATE", "download_url":"https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1173491", "matches_corpus_cavernosum_fibroblast":"NO", "evidence_status":"VERIFIED_DATASET_MEMBER", "source_url":"https://s3.perturbseqr.maayanlab.cloud/data/cm4ai.gmt.gz", "primary_citation":"Nourreddine et al., Nature Biotechnology (2026), doi:10.1038/s41587-026-03199-w", "notes":"Target membership is machine-readable in the public PerturbSeqr CM4AI GMT as TYMS::KOLF2.1J::hiPSCs::144H::::KD::CRISPRi. Raw read project is public; processed-object privacy is retained as a separate accessibility qualifier.", "evidence_ids":"E08;E09;E10"},
        {"target_gene":"TYMS", "canonical_symbol_verified":"YES_NCBI_Gene_7298", "perturbation_type":"NOT_APPLICABLE", "single_or_combination":"NOT_APPLICABLE", "cell_line_or_type":"NOT_APPLICABLE", "cell_context_tier":"TX_UNKNOWN", "species":"NOT_VERIFIED", "time":"NOT_REPORTED", "dose_or_intensity":"NOT_REPORTED", "dataset":"GSE253847", "accession":"GSE253847", "has_controls":"NOT_VERIFIED", "downloadable":"NOT_ASSESSED", "download_url":"https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE253847", "matches_corpus_cavernosum_fibroblast":"NO", "evidence_status":"SEARCH_HIT_NOT_COVERAGE", "source_url":"ncbi_search_results.json", "primary_citation":"NOT_APPLICABLE", "notes":"Frozen snapshot hit was screened as target mention/animal metabolic-rewiring study, not an audited direct human TYMS perturbation transcriptome. Retained to prevent silent exclusion.", "evidence_ids":"E03;E17"},
        {"target_gene":"LRRC17", "canonical_symbol_verified":"YES_NCBI_Gene_10234", "perturbation_type":"NOT_APPLICABLE", "single_or_combination":"NOT_APPLICABLE", "cell_line_or_type":"intestinal myofibroblast and skin fibroblast", "cell_context_tier":"TX_UNKNOWN", "species":"NOT_VERIFIED", "time":"NOT_REPORTED", "dose_or_intensity":"NOT_REPORTED", "dataset":"Intestinal myofibroblast vs skin fibroblast", "accession":"GSE77474", "has_controls":"NOT_VERIFIED", "downloadable":"NOT_ASSESSED", "download_url":"https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE77474", "matches_corpus_cavernosum_fibroblast":"NO", "evidence_status":"SEARCH_HIT_NOT_COVERAGE", "source_url":"ncbi_search_results.json", "primary_citation":"NOT_APPLICABLE", "notes":"Frozen snapshot hit has no verified direct LRRC17 genetic perturbation; it is retained as a search hit, not promoted to coverage.", "evidence_ids":"E02;E18"},
    ]
    write_tsv(OUTPUTS[0], coverage, coverage_fields)

    search_fields = ["search_id", "target_gene", "source_family", "database_or_catalogue", "endpoint_or_url", "query_or_record", "accessed_at_utc", "server_count", "retrieved_count", "screened_count", "local_filter_or_outcome", "snapshot_or_source"]
    search_rows: list[dict[str, str]] = []
    for index, item in enumerate(snapshot["searches"], start=1):
        meta = item["search"]
        search_rows.append({"search_id":f"NCBI_{index:02d}", "target_gene":item["target_gene"], "source_family":item["query_family"], "database_or_catalogue":meta["db"], "endpoint_or_url":meta["endpoint"], "query_or_record":meta["term"], "accessed_at_utc":snapshot["accessed_at_utc"], "server_count":str(meta["server_count"]), "retrieved_count":str(meta["retrieved_count"]), "screened_count":str(meta["retrieved_count"]), "local_filter_or_outcome":"Raw sealed query retained; qualifying records and exclusions transcribed in coverage/source evidence.", "snapshot_or_source":"ncbi_search_results.json"})
    search_rows.extend([
        {"search_id":"CAT_01", "target_gene":"EFNB2;LRRC17;TYMS", "source_family":"catalogue", "database_or_catalogue":"PerturbSeqr CM4AI GMT", "endpoint_or_url":"https://s3.perturbseqr.maayanlab.cloud/data/cm4ai.gmt.gz", "query_or_record":"exact canonical symbol in GMT term header", "accessed_at_utc":accessed, "server_count":"NOT_APPLICABLE", "retrieved_count":"4 target-direction signatures", "screened_count":"4", "local_filter_or_outcome":"EFNB2 and TYMS exact CRISPRi records retained; LRRC17 has no exact term in this GMT.", "snapshot_or_source":"E08"},
        {"search_id":"CAT_02", "target_gene":"TYMS", "source_family":"catalogue", "database_or_catalogue":"Harmonizome Replogle K562 genome-wide target record", "endpoint_or_url":"https://maayanlab.cloud/Harmonizome/gene_set/9464_TYMS_P1P2/Replogle%2Bet%2Bal.%2C%2BCell%2C%2B2022%2BK562%2BGenome-wide%2BPerturb-seq%2BGene%2BPerturbation%2BSignatures", "query_or_record":"9464_TYMS_P1P2", "accessed_at_utc":accessed, "server_count":"NOT_APPLICABLE", "retrieved_count":"1", "screened_count":"1", "local_filter_or_outcome":"Exact TYMS CRISPRi K562 day-8 record retained.", "snapshot_or_source":"E15"},
        {"search_id":"CAT_03", "target_gene":"EFNB2;LRRC17;TYMS", "source_family":"catalogue", "database_or_catalogue":"scPerturb official resource", "endpoint_or_url":"https://github.com/sanderlab/scPerturb", "query_or_record":"catalogue availability and declared download route", "accessed_at_utc":accessed, "server_count":"NOT_APPLICABLE", "retrieved_count":"NOT_APPLICABLE", "screened_count":"NOT_APPLICABLE", "local_filter_or_outcome":"Source route recorded; no per-target negative conclusion is inferred because its public catalogue page has no stable exact-target query endpoint used here.", "snapshot_or_source":"E19"},
        {"search_id":"CAT_04", "target_gene":"EFNB2;LRRC17;TYMS", "source_family":"catalogue", "database_or_catalogue":"PerturbLab official repository", "endpoint_or_url":"https://github.com/krkawzq/PerturbLab", "query_or_record":"public resource registry route", "accessed_at_utc":accessed, "server_count":"NOT_APPLICABLE", "retrieved_count":"NOT_APPLICABLE", "screened_count":"NOT_APPLICABLE", "local_filter_or_outcome":"Source route recorded; it was not used as a target-membership assertion or as a negative search result.", "snapshot_or_source":"E20"},
        {"search_id":"CAT_05", "target_gene":"EFNB2;LRRC17;TYMS", "source_family":"catalogue", "database_or_catalogue":"GEARS official repository", "endpoint_or_url":"https://github.com/snap-stanford/GEARS", "query_or_record":"processed Replogle K562-essential/RPE1-essential dataset availability and stated model constraints", "accessed_at_utc":accessed, "server_count":"NOT_APPLICABLE", "retrieved_count":"2 processed subsets", "screened_count":"2", "local_filter_or_outcome":"No cross-cell prediction performed; source constrains applicability only.", "snapshot_or_source":"E11"},
    ])
    write_tsv(OUTPUTS[1], search_rows, search_fields)

    evidence_fields = ["evidence_id", "target_gene", "source_family", "source_name", "source_url", "accessed_at_utc", "endpoint_or_record", "evidence_level", "finding", "inclusion_decision", "limitations"]
    evidence = [
        {"evidence_id":f"E{idx:02d}", "target_gene":target, "source_family":"NCBI Gene", "source_name":"NCBI Gene exact human-symbol resolution", "source_url":f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=gene&term={target}%5Bgene%5D%20AND%20Homo%20sapiens%5Borgn%5D&retmode=json", "accessed_at_utc":accessed, "endpoint_or_record":f"NCBI Gene {gid}", "evidence_level":"PRIMARY_DATABASE", "finding":f"One Homo sapiens record resolved for canonical symbol {target}.", "inclusion_decision":"canonical-symbol verification", "limitations":"Identity resolution only; not perturbation evidence."}
        for idx, (target, gid) in enumerate(genes.items(), start=1)
    ]
    evidence += [
        {"evidence_id":"E04", "target_gene":"EFNB2", "source_family":"NCBI GEO", "source_name":"GSE279328 SOFT", "source_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE279nnn/GSE279328/soft/GSE279328_family.soft.gz", "accessed_at_utc":accessed, "endpoint_or_record":"GSE279328", "evidence_level":"PRIMARY_DATABASE", "finding":"Ad-Efnb2 versus Ad-NC LEC bulk RNA-seq under hypoxia; 4 OE and 3 NC sample labels.", "inclusion_decision":"coverage", "limitations":"Time and vector dose not reported; raw-file loss warning retained."},
        {"evidence_id":"E05", "target_gene":"EFNB2", "source_family":"NCBI GEO", "source_name":"GSE279328 public series endpoint", "source_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE279nnn/GSE279328/", "accessed_at_utc":accessed, "endpoint_or_record":"GSE279328", "evidence_level":"PRIMARY_DATABASE", "finding":"Public GEO series and supplementary endpoint reachable.", "inclusion_decision":"downloadability", "limitations":"Endpoint reachability is not a claim that missing raw reads were restored."},
        {"evidence_id":"E06", "target_gene":"EFNB2", "source_family":"NCBI GEO", "source_name":"GSE256290 SOFT", "source_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE256nnn/GSE256290/soft/GSE256290_family.soft.gz", "accessed_at_utc":accessed, "endpoint_or_record":"GSE256290", "evidence_level":"PRIMARY_DATABASE", "finding":"dCas9-VPR U266 CRISPRa; 5 EFNB2-gRNA2 and 5 scrambled cgRNA samples.", "inclusion_decision":"coverage", "limitations":"Bulk cancer-cell-line context; time not reported."},
        {"evidence_id":"E07", "target_gene":"EFNB2", "source_family":"NCBI GEO", "source_name":"GSE256290 public series endpoint", "source_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE256nnn/GSE256290/", "accessed_at_utc":accessed, "endpoint_or_record":"GSE256290", "evidence_level":"PRIMARY_DATABASE", "finding":"Public processed-count and raw-read-quantification supplementary URLs listed.", "inclusion_decision":"downloadability", "limitations":"No cross-cell generalization follows."},
        {"evidence_id":"E08", "target_gene":"EFNB2;TYMS", "source_family":"PerturbSeqr", "source_name":"CM4AI machine-readable GMT", "source_url":"https://s3.perturbseqr.maayanlab.cloud/data/cm4ai.gmt.gz", "accessed_at_utc":accessed, "endpoint_or_record":"EFNB2 and TYMS 144H KOLF2.1J hiPSC CRISPRi term headers", "evidence_level":"DERIVED_CATALOGUE", "finding":"Exact terms EFNB2::KOLF2.1J::hiPSCs::144H::::KD::CRISPRi and TYMS::KOLF2.1J::hiPSCs::144H::::KD::CRISPRi were found; no LRRC17 exact term found.", "inclusion_decision":"target membership", "limitations":"Derived catalogue confirms annotated signature membership, not access to a full processed object."},
        {"evidence_id":"E09", "target_gene":"EFNB2;TYMS", "source_family":"NCBI BioProject", "source_name":"CM4AI raw scRNA-seq BioProject", "source_url":"https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1173491", "accessed_at_utc":accessed, "endpoint_or_record":"PRJNA1173491", "evidence_level":"PRIMARY_DATABASE", "finding":"Public raw scRNA-seq and CRISPR dial-out project for KOLF2.1J hiPSC Pan-Expressed Genome Perturb-Seq.", "inclusion_decision":"raw-data accessibility", "limitations":"Raw data accessibility is separate from processed-object availability."},
        {"evidence_id":"E10", "target_gene":"EFNB2;TYMS", "source_family":"primary article", "source_name":"CM4AI perturbation atlas", "source_url":"https://www.nature.com/articles/s41587-026-03199-w", "accessed_at_utc":accessed, "endpoint_or_record":"doi:10.1038/s41587-026-03199-w", "evidence_level":"PRIMARY_ARTICLE", "finding":"Genome-scale hiPSC CRISPRi Perturb-Seq study documents non-targeting controls and target/NTC comparison framework.", "inclusion_decision":"controls/context", "limitations":"hiPSC context is T3, not corpus-cavernosum fibroblast."},
        {"evidence_id":"E11", "target_gene":"EFNB2;LRRC17;TYMS", "source_family":"GEARS", "source_name":"GEARS official repository", "source_url":"https://github.com/snap-stanford/GEARS", "accessed_at_utc":accessed, "endpoint_or_record":"README usage note", "evidence_level":"OFFICIAL_SOFTWARE", "finding":"GEARS provides processed Replogle K562-essential/RPE1-essential loaders and states it is not designed for cross-cell-type transfer; single-gene-only training cannot reliably predict combinations.", "inclusion_decision":"applicability constraint", "limitations":"Software documentation is not external biological validation."},
        {"evidence_id":"E12", "target_gene":"LRRC17", "source_family":"frozen NCBI snapshot", "source_name":"sealed bounded NCBI search", "source_url":"ncbi_search_results.json", "accessed_at_utc":snapshot["accessed_at_utc"], "endpoint_or_record":"18 frozen GDS/PubMed searches", "evidence_level":"SEALED_SEARCH", "finding":"No qualifying direct LRRC17 coverage was promoted after screening; GSE77474 is retained as non-coverage.", "inclusion_decision":"bounded NO_VERIFIED_HIT", "limitations":"Not a global nonexistence claim."},
        {"evidence_id":"E13", "target_gene":"TYMS", "source_family":"NCBI GEO", "source_name":"GSE148589 SOFT", "source_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE148nnn/GSE148589/soft/GSE148589_family.soft.gz", "accessed_at_utc":accessed, "endpoint_or_record":"GSE148589", "evidence_level":"PRIMARY_DATABASE", "finding":"A549 shTS knockdown and scrambled pLKO control each have two RNA-seq replicates.", "inclusion_decision":"coverage", "limitations":"Bulk cancer-cell-line context; time and perturbation dose not reported."},
        {"evidence_id":"E14", "target_gene":"TYMS", "source_family":"NCBI GEO", "source_name":"GSE148589 public series endpoint", "source_url":"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE148nnn/GSE148589/", "accessed_at_utc":accessed, "endpoint_or_record":"GSE148589", "evidence_level":"PRIMARY_DATABASE", "finding":"Public count and FPKM supplementary matrices and SRA relationship are listed.", "inclusion_decision":"downloadability", "limitations":"Calu-1 TS-high/low reporter sorting is not counted as a direct TYMS perturbation row."},
        {"evidence_id":"E15", "target_gene":"TYMS", "source_family":"Harmonizome", "source_name":"Replogle K562 genome-wide target record", "source_url":"https://maayanlab.cloud/Harmonizome/gene_set/9464_TYMS_P1P2/Replogle%2Bet%2Bal.%2C%2BCell%2C%2B2022%2BK562%2BGenome-wide%2BPerturb-seq%2BGene%2BPerturbation%2BSignatures", "accessed_at_utc":accessed, "endpoint_or_record":"9464_TYMS_P1P2", "evidence_level":"DERIVED_CATALOGUE", "finding":"Public exact target record labels CRISPR interference perturbation targeting TYMS P1P2 in Replogle K562 genome-wide signatures.", "inclusion_decision":"target membership", "limitations":"Derived record; no claim about GEARS filtered subsets."},
        {"evidence_id":"E16", "target_gene":"TYMS", "source_family":"Figshare", "source_name":"Replogle processed Perturb-seq dataset", "source_url":"https://api.figshare.com/v2/articles/20029387", "accessed_at_utc":accessed, "endpoint_or_record":"file 35774443 K562_gwps_raw_bulk_01.h5ad", "evidence_level":"PRIMARY_REPOSITORY", "finding":"Public Figshare article lists public K562 genome-wide processed AnnData endpoints; study is day-8 K562 genome-scale Perturb-seq.", "inclusion_decision":"downloadability/context", "limitations":"No full H5AD matrix was used as a biological test in this audit."},
        {"evidence_id":"E17", "target_gene":"TYMS", "source_family":"frozen NCBI snapshot", "source_name":"GSE253847 screen record", "source_url":"ncbi_search_results.json", "accessed_at_utc":snapshot["accessed_at_utc"], "endpoint_or_record":"GSE253847", "evidence_level":"SEALED_SEARCH", "finding":"Search hit retained for screening traceability.", "inclusion_decision":"SEARCH_HIT_NOT_COVERAGE", "limitations":"Does not establish direct human TYMS genetic perturbation transcriptomic coverage."},
        {"evidence_id":"E18", "target_gene":"LRRC17", "source_family":"frozen NCBI snapshot", "source_name":"GSE77474 screen record", "source_url":"ncbi_search_results.json", "accessed_at_utc":snapshot["accessed_at_utc"], "endpoint_or_record":"GSE77474", "evidence_level":"SEALED_SEARCH", "finding":"Intestinal-myofibroblast versus skin-fibroblast record has no verified direct LRRC17 perturbation.", "inclusion_decision":"SEARCH_HIT_NOT_COVERAGE", "limitations":"Retained as an exclusion rather than recast as coverage."},
        {"evidence_id":"E19", "target_gene":"EFNB2;LRRC17;TYMS", "source_family":"scPerturb", "source_name":"scPerturb official resource", "source_url":"https://github.com/sanderlab/scPerturb", "accessed_at_utc":accessed, "endpoint_or_record":"README data route", "evidence_level":"OFFICIAL_CATALOGUE", "finding":"Official resource states data are available on scperturb.org/Zenodo and downloadable through supported routes.", "inclusion_decision":"source-route provenance only", "limitations":"No stable exact-target query endpoint was used; this row cannot support a negative target claim."},
        {"evidence_id":"E20", "target_gene":"EFNB2;LRRC17;TYMS", "source_family":"PerturbLab", "source_name":"PerturbLab official repository", "source_url":"https://github.com/krkawzq/PerturbLab", "accessed_at_utc":accessed, "endpoint_or_record":"dataset resource registry", "evidence_level":"OFFICIAL_SOFTWARE", "finding":"Repository exposes a public dataset registry and loaders for scPerturb benchmark data.", "inclusion_decision":"source-route provenance only", "limitations":"Not used as target membership or a negative target result."},
    ]
    write_tsv(OUTPUTS[2], evidence, evidence_fields)

    gears_fields = ["target_gene", "best_available_context", "best_context_tier", "real_target_perturbation", "single_cell_transcriptome", "controls_verified", "downloadable", "gears_adjudication", "is_direct_external_reference", "reason", "boundary"]
    gears = [
        {"target_gene":"EFNB2", "best_available_context":"KOLF2.1J hiPSC CRISPRi (T3); LEC bulk OE (T2)", "best_context_tier":"T3_OTHER_PRIMARY_HUMAN", "real_target_perturbation":"YES", "single_cell_transcriptome":"YES_in_T3_only", "controls_verified":"YES_in_CM4AI", "downloadable":"YES_raw_SRA", "gears_adjudication":"ALGORITHMIC_OR_GENERAL_FUNCTION_REFERENCE", "is_direct_external_reference":"NO", "reason":"No T1 corpus-cavernosum fibroblast record. GEARS prohibits cross-cell-type transfer; bulk LEC data cannot satisfy GEARS training coverage.", "boundary":"No GEARS prediction was run or called validation."},
        {"target_gene":"LRRC17", "best_available_context":"NO_VERIFIED_HIT", "best_context_tier":"TX_UNKNOWN", "real_target_perturbation":"NO", "single_cell_transcriptome":"NO", "controls_verified":"NOT_VERIFIED", "downloadable":"NOT_VERIFIED", "gears_adjudication":"NOT_VALIDATION", "is_direct_external_reference":"NO", "reason":"No qualifying target perturbation was verified in frozen sources.", "boundary":"Zero-shot prediction cannot serve as validation."},
        {"target_gene":"TYMS", "best_available_context":"K562 genome-wide CRISPRi (T4); KOLF2.1J hiPSC CRISPRi (T3)", "best_context_tier":"T3_OTHER_PRIMARY_HUMAN", "real_target_perturbation":"YES", "single_cell_transcriptome":"YES_in_T3_or_T4", "controls_verified":"NOT_VERIFIED_IN_REPLOGLE_TARGET_RECORD;YES_in_CM4AI", "downloadable":"YES", "gears_adjudication":"ALGORITHMIC_OR_GENERAL_FUNCTION_REFERENCE", "is_direct_external_reference":"NO", "reason":"All verified contexts are non-cavernosal and GEARS cross-cell transfer is disallowed. The GEARS processed essential subset must not be conflated with full K562_gwps.", "boundary":"Single-gene data cannot validate any combination perturbation."},
    ]
    write_tsv(OUTPUTS[3], gears, gears_fields)

    unipert = {
        "gate":"VP-G07", "generated_at_utc":accessed, "unipert_status":"SOFTWARE_SCOPE_AUDITED_NO_ENCODING_EXECUTED", "unipert_allowed_claims":["representation only", "nearest-neighbour ranking only if reproducible checkpoint is separately pinned"], "prohibited_claims":["expression reversal", "efficacy in corpus-cavernosum cells", "experimental validation", "drug recommendation without matched effect data"], "g2cp_status":"NOT_APPLICABLE_YET", "g2cp_start_conditions":[
            {"condition":"same human target-cell background", "status":"UNMET", "evidence":"No T1 human corpus-cavernosum fibroblast perturbation record; verified records span LEC, hiPSC, U266, A549, and K562."},
            {"condition":"real TYMS/EFNB2/LRRC17 genetic-perturbation transcriptomes", "status":"UNMET", "evidence":"EFNB2 and TYMS have records in mismatched contexts; LRRC17 is NO_VERIFIED_HIT, so no matched three-target set exists."},
            {"condition":"small matched-background candidate-drug transcriptome set", "status":"UNMET", "evidence":"No such dataset was introduced in the frozen scope."},
            {"condition":"fixed time, dose, oxygen condition, and negative controls", "status":"UNMET", "evidence":"The available public records do not constitute one matched experimental panel with all frozen covariates."},
            {"condition":"held-out unseen-drug and unseen-donor evaluation", "status":"UNMET", "evidence":"No matched training/evaluation panel exists."}
        ], "interpretation_boundary":"NOT_APPLICABLE_YET is a data-design state, not a failure of target biology. No UniPert embedding, drug ranking, or G2CP prediction was generated."
    }
    OUTPUTS[4].write_text(json.dumps(unipert, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    report = f"""# VP-G07 公共遗传扰动覆盖审计\n\n生成时间：`{accessed}`。本报告只完成已冻结 VP-G07 的外部覆盖审计；不启动 VP-G08。\n\n## 技术结论\n\n- 三个固定靶点均有显式覆盖行：EFNB2 3 条真实遗传扰动记录、TYMS 3 条真实遗传扰动记录、LRRC17 1 条有界 `NO_VERIFIED_HIT` 记录。\n- 没有任何记录为人海绵体成纤维细胞（T1_EXACT）；因此不存在直接外部参照。\n- GEARS 未执行跨细胞型预测。EFNB2/TYMS 最多是 T3/T4 的算法或一般功能参照；LRRC17 为 `NOT_VALIDATION`。\n- UniPert-G2CP 五项启动条件均未满足，状态为 `NOT_APPLICABLE_YET`；没有生成蛋白表示、药物排序或任何疗效推断。\n\n## 覆盖边界\n\n`NO_VERIFIED_HIT` 仅表示在封存的 NCBI 检索与此处记录的定向官方来源中没有获得合格记录，绝不表示全球不存在。NCBI 原始 18 次查询仍保留在 `ncbi_search_results.json`，未被重跑或覆盖。\n\n## 可解释性边界\n\n本项目的 scTenifoldKnk 结果和本审计中的 T2--T5 外部记录都不能证明海绵体成纤维细胞中的因果机制、ED 表达逆转或治疗获益。公开 bulk 数据不能满足 Perturb-seq/GEARS 训练覆盖；单基因记录也不能验证组合扰动。\n\n## 主要可追溯来源\n\n- GSE279328、GSE256290、GSE148589 的 GEO SOFT 记录（见 `source_evidence.tsv`）。\n- Replogle K562 genome-wide `9464_TYMS_P1P2` 目标记录及公开 Figshare AnnData 端点。\n- CM4AI KOLF2.1J hiPSC 的公开原始 SRA BioProject 和 PerturbSeqr 的机器可读 GMT 目标条目。\n- GEARS 官方 README 的跨细胞型与组合预测限制。\n\n所有逐行字段、缺失值、排除项、URL 和检索计数均位于同目录的 TSV/JSON 产物中。\n"""
    OUTPUTS[5].write_text(report, encoding="utf-8")

    manifest_rows = []
    for path in OUTPUTS[:-1]:
        manifest_rows.append({"relative_path":str(path.relative_to(VP)).replace("\\\\", "/"), "sha256":sha256(path), "bytes":str(path.stat().st_size)})
    write_tsv(OUTPUTS[6], manifest_rows, ["relative_path", "sha256", "bytes"])
    print(json.dumps({"status":"BUILT_NO_OVERWRITE", "outputs":[str(path) for path in OUTPUTS], "accessed_at_utc":accessed}, ensure_ascii=False))


if __name__ == "__main__":
    main()
