args <- commandArgs(trailingOnly = TRUE); if (length(args) != 1L) stop("Usage: Rscript 09h_run_es01_influence_analysis.R <vp_root>", call.=FALSE)
vp_root <- normalizePath(args[[1]], winslash="/", mustWork=TRUE); project_root <- normalizePath(file.path(vp_root,"../.."),winslash="/",mustWork=TRUE)
attempt <- file.path(vp_root,"10_exploratory_hypoxia_sensitivity","attempt_20260910_02"); .libPaths(c(file.path(vp_root,"02_env","Rlib"),.libPaths()))
suppressPackageStartupMessages({library(data.table);library(fgsea);library(jsonlite);library(digest)})
outs <- file.path(attempt,c("04_leave_one_seed_out.tsv","04_leave_one_donor_out.tsv","04_donor_heterogeneity.tsv")); if(any(file.exists(outs)))stop("Refusing to overwrite ES01-04 outputs.",call.=FALSE)
scope<-fromJSON(file.path(attempt,"01_scope_freeze.json"),simplifyVector=FALSE); if(!identical(scope$status,"FROZEN_EXPLORATORY_SPECIFICATION"))stop("Scope not frozen.",call.=FALSE)
seed_hyp<-fread(file.path(attempt,"03_target_donor_seed_hypoxia.tsv")); if(nrow(seed_hyp)!=45L||any(!is.finite(seed_hyp$NES)))stop("ES01-03 seed hypoxia output invalid.",call.=FALSE)
g06<-fromJSON(file.path(vp_root,"01_protocol","VP_G06_enrichment_rule_freeze_v1.json"),simplifyVector=FALSE); gmt<-file.path(project_root,"analysis","data","processed","gene_sets","Hallmark.gmt")
if(!identical(digest(file=gmt,algo="sha256"),g06$input_sha256[["analysis/data/processed/gene_sets/Hallmark.gmt"]]))stop("HOLD_INPUT_DRIFT Hallmark GMT.",call.=FALSE)
universe<-fread(file.path(vp_root,"04_prepared","gene_universe.tsv"))$gene; if(length(universe)!=1388L||anyDuplicated(universe))stop("Universe mismatch.",call.=FALSE)
read_gmt<-function(p){x<-strsplit(readLines(p,warn=FALSE,encoding="UTF-8"),"\t",fixed=TRUE); z<-lapply(x,function(a)unique(a[-c(1L,2L)]));names(z)<-vapply(x,`[[`,character(1),1L);z}
sets<-lapply(read_gmt(gmt),intersect,y=universe); sets<-sets[lengths(sets)>=15L&lengths(sets)<=500L]
formal_elig<-fread(file.path(vp_root,"07_enrichment","v1","gene_set_eligibility.tsv"))[database=="Hallmark"&status=="TESTED",pathway];if(!identical(sort(names(sets)),sort(formal_elig)))stop("Formal Hallmark family mismatch.",call.=FALSE)
rank_from_distance<-function(dt){setorderv(dt,c("distance","gene"),c(-1L,1L));setNames((nrow(dt)-seq_len(nrow(dt))+1)/nrow(dt),dt$gene)}
aggregate_ranks<-function(rank_list){m<-do.call(cbind,rank_list);score<-apply(m,1L,median);o<-order(-score,names(score));setNames((length(score)-seq_along(score)+1)/length(score),names(score)[o])}
run<-function(ranks,seed){set.seed(seed);x<-suppressWarnings(fgseaMultilevel(sets,ranks,minSize=15L,maxSize=500L,eps=0,scoreType="std",nproc=1L));x[,leading_edge:=vapply(leadingEdge,paste,collapse=";",character(1))];x[,leading_edge_size:=lengths(leadingEdge)];x[,pathway:=as.character(pathway)];x[,abs_sort:=-abs(NES)];setorder(x,padj,abs_sort,pathway,na.last=TRUE);x[,abs_sort:=NULL];x[,hallmark_rank:=seq_len(.N)];x[pathway=="HALLMARK_HYPOXIA"]}
jaccard<-function(a,b){x<-strsplit(a,";",fixed=TRUE)[[1]];y<-strsplit(b,";",fixed=TRUE)[[1]];if(identical(a,"") )x<-character();if(identical(b,""))y<-character();length(intersect(x,y))/length(union(x,y))}
reg<-fread(file.path(vp_root,"05_runs","run_registry.tsv"));setorder(reg,gene,condition,donor,seed); if(nrow(reg)!=45L||any(reg$status!="PASS_TECHNICAL"))stop("Registry invalid.",call.=FALSE)
seed_maps<-list();for(i in seq_len(nrow(reg))){d<-fread(file.path(reg$output_attempt[i],"differential_regulation.tsv"),select=c("gene","distance"));if(nrow(d)!=1388L||anyDuplicated(d$gene)||!setequal(d$gene,universe)||any(!is.finite(d$distance)))stop("Raw seed rank invalid.",call.=FALSE);seed_maps[[reg$run_id[i]]]<-rank_from_distance(d)}
formal_donor<-fread(file.path(vp_root,"07_enrichment","v1","hypoxia_donor_enrichment.tsv"))[pathway=="HALLMARK_HYPOXIA"]
formal_primary<-fread(file.path(vp_root,"07_enrichment","v1","hypoxia_primary_summary.tsv"))
counter<-as.integer(g06$method$random_seed);los<-list();lod<-list()
groups<-unique(reg[,.(gene,condition,donor)]);setorder(groups,gene,condition,donor)
for(i in seq_len(nrow(groups))){g<-groups[i];runs<-reg[gene==g$gene&condition==g$condition&donor==g$donor];setorder(runs,seed);ref<-formal_donor[target_gene==g$gene&condition==g$condition&donor==g$donor];for(j in seq_len(nrow(runs))){keep<-runs[-j];ranks<-aggregate_ranks(lapply(keep$run_id,function(id)seed_maps[[id]]));counter<-counter+1L;x<-run(ranks,counter);los[[length(los)+1L]]<-data.table(target_gene=g$gene,condition=g$condition,donor=g$donor,excluded_seed=as.character(runs$seed[j]),included_seeds=paste(keep$seed,collapse=";"),call_seed=counter,ES=x$ES,NES=x$NES,p_value=x$pval,FDR_within_Hallmark=x$padj,leading_edge=x$leading_edge,leading_edge_size=x$leading_edge_size,hallmark_rank=x$hallmark_rank,formal_five_seed_NES=ref$NES,leading_edge_jaccard_vs_formal=jaccard(x$leading_edge,ref$leadingEdge))}}
rankings<-fread(file.path(vp_root,"06_consensus","all_virtual_KO_rankings.tsv.gz"));
for(t in unique(groups[,.(gene,condition)]$gene)){cond<-unique(groups[gene==t]$condition);ds<-sort(unique(groups[gene==t&condition==cond]$donor));for(ex in ds){keep<-setdiff(ds,ex);rmaps<-lapply(keep,function(d){z<-rankings[target_gene==t&condition==cond&donor==d,.(gene,median_standardized_rank)];setorderv(z,c("median_standardized_rank","gene"),c(-1L,1L));setNames((nrow(z)-seq_len(nrow(z))+1)/nrow(z),z$gene)});ranks<-aggregate_ranks(rmaps);counter<-counter+1L;x<-run(ranks,counter);ref<-formal_primary[target_gene==t&condition==cond];lod[[length(lod)+1L]]<-data.table(target_gene=t,condition=cond,excluded_donor=ex,included_donors=paste(keep,collapse=";"),call_seed=counter,ES=x$ES,NES=x$NES,p_value=x$pval,FDR_within_Hallmark=x$padj,leading_edge=x$leading_edge,leading_edge_size=x$leading_edge_size,hallmark_rank=x$hallmark_rank,formal_three_donor_NES=ref$NES,leading_edge_jaccard_vs_formal=jaccard(x$leading_edge,ref$leadingEdge))}}
los<-rbindlist(los);lod<-rbindlist(lod);het<-seed_hyp[,.(donor_NES_median=median(NES)),by=.(target_gene,condition,donor)][,.(donors=.N,donor_NES_median=median(donor_NES_median),donor_NES_min=min(donor_NES_median),donor_NES_max=max(donor_NES_median),donor_NES_MAD=mad(donor_NES_median,constant=1),positive_NES_donor_count=sum(donor_NES_median>0),negative_NES_donor_count=sum(donor_NES_median<0),unweighted_sum_squared_deviation=sum((donor_NES_median-mean(donor_NES_median))^2),heterogeneity_description="Descriptive across-donor dispersion only; no asymptotic heterogeneity inference at n=3."),by=.(target_gene,condition)]
if(nrow(los)!=45L||nrow(lod)!=9L||nrow(het)!=3L)stop("Influence output cardinality mismatch.",call.=FALSE);fwrite(los,outs[1],sep="\t");fwrite(lod,outs[2],sep="\t");fwrite(het,outs[3],sep="\t");cat(toJSON(list(gate="VP-ES01-04",status="PASS_COMPUTED_PENDING_NEXT_GATE",leave_one_seed=nrow(los),leave_one_donor=nrow(lod)),auto_unbox=TRUE),"\n")
